### ISSUE TITLE
DeprecationWarning in task/models.py

### ISSUE THREAD

**Issue by vfdev-5** [allegroai/clearml#376] opened 2021-06-02 12:33 UTC
Sorry for a duplicated issue or if already fixed (in this please close the issue).

I see the following deprecation warning with `clearml==1.0.2` installed with pip.
```
python3.8/site-packages/clearml/backend_interface/task/models.py:38: DeprecationWarning: Flags not at the start of the expression '((?i)(Using model id' (truncated)    
    _input_models_re = re.compile(r"((?i)(Using model id: )(\w+)?)")
```

Thanks

**Comment by jkhenning** [comment] 2021-06-02 19:03
Hi @vfdev-5,

Thanks for bringing this to our attention 👍 
Although for some reason I couldn't reproduce this deprecation warning with a pip install in a clean Python 3.8 venv, the above mentioned Regex usage is indeed deprecated, and we'll fix it soon 🙂

**Comment by jkhenning** [comment] 2023-03-15 13:50
Closing this as this was already released. Please reopen if required.

**Closed by jkhenning** 2023-03-15 13:50 UTC
