### ISSUE TITLE
Dataset.create() doesn't use default_output_uri setting from clearml.conf 

### ISSUE THREAD

**Issue by ogorun** [allegroai/clearml#371] opened 2021-05-31 08:25 UTC
Task.init() takes by default output_uri from clearml.conf configuration file (S3 bucket in my case). But underlined task created with Dataset.create() ignores it and uploads files by default to https://files.community.clear.ml 

Steps to reproduce:

clearml.conf contains setting:
sdk.development.default_output_uri = "s3://anyclip-edison/clearml"

```
task = Task.init(project_name=PROJECT_NAME, task_name=section)
dataset = Dataset.create(dataset_name='some_ds', dataset_project=PROJECT_NAME)
# dataset._task.output_uri = task.output_uri
dataset.add_files(DOCS_ROOT, wildcard='*.csv')
dataset.upload()
```

Without commented line DOCS_ROOT directory content is uploaded not to S3 bucket but to https://files.community.clear.ml 

Versions:
clearml==1.0.2
OS: Ubuntu 18

pip list is attached.
[pip-list.txt](https://github.com/allegroai/clearml/files/6568862/pip-list.txt)

**Comment by bmartinn** [comment] 2021-05-31 19:44
Thanks @ogorun !
The issue is verified, a fix is coming up...
I'll update here once we have an RC out

**Comment by bmartinn** [comment] 2021-06-01 22:04
Hi @ogorun 
Fix is included in the latest RC, could you verify?
```
pip install clearml==1.0.4rc0
```

**Comment by ogorun** [comment] 2021-06-07 09:09
@bmartinn Oh, I just saw this comment. Sorry. It works now. Thank you

**Closed** 2021-06-14 22:27 UTC
