### ISSUE TITLE
Docstrings / documentation for  `close` and `mark_completed` is lacking

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml#929] opened 2023-02-21 10:54 UTC
The documentation for `close` and `mark_completed`, namely the docstrings

- https://clear.ml/docs/latest/docs/references/sdk/task/#mark_completed
- https://clear.ml/docs/latest/docs/references/sdk/task/#close

is lacking. I made a pull request to improve them, but going by https://app.slack.com/client/TT9ATQXJ5/CTK20V944/thread/CTK20V944-1676556098.205589, this has by far not clarified everything. The following questions require answers:

1. Is the new documentation right?
2. When are `close` and `mark_completed` supposed to be used in terms of "workflow"?
3. Why does `close` not kill the process that calls it, but `mark_completed` does?
4. Are  `close` and `mark_completed` supposed to be used from the same process that created the respective task or from a different process or both - what are here the ideas?

If someone explains it here, I can make a pull request, but I am out of my depth knowledge wise.

**Comment by eugen-ajechiloae-clearml** [comment] 2023-02-22 22:21
Duplicate of: https://github.com/allegroai/clearml/issues/928 (clarified there)

**Closed by eugen-ajechiloae-clearml** 2023-02-22 22:21 UTC
