### ISSUE TITLE
Circular reference error

### ISSUE THREAD

**Issue by ColdTeapot273K** [allegroai/clearml#510] opened 2021-12-07 06:35 UTC
When trying to log pandas dataframe constructed via function, an error occurs. 
Using `.copy(deep=True)` doesn't help.

Example code:
```python
from sklego.model_selection import TimeGapSplit
from datetime import timedelta

cv = TimeGapSplit(
    date_serie=df.reset_index("time").loc[:, "time"],
    train_duration=timedelta(days=7),
    valid_duration=timedelta(days=1),
    gap_duration=timedelta(days=0),
    n_splits=3,
)


table_plot = cv.summary(df)
title = "cross-validation folds"
series = "1"
Logger.current_logger().report_table(title=title, series=series, table_plot=table_plot)
```

Actual result:
```python
ValueError: Circular reference detected
```

UPD: 
This did not help:
```python
df_ = cv.summary(df_dev)
_df = pd.DataFrame(data=df_.values, index=df_.index, columns=df_.columns)

table_plot = _df
title = "cross-validation folds"
series = "1"
Logger.current_logger().report_table(title=title, series=series, table_plot=table_plot)
```

**Comment by jkhenning** [comment] 2021-12-07 20:30
Hi @ColdTeapot273K,

Can you also include the creation of `df` in the example?

**Comment by ColdTeapot273K** [comment] 2021-12-08 06:15
Hi @jkhenning 

I think i can decouple it from the library even; here's a self-contained example:

```python
from pandas import Timestamp, Timedelta
dict_repr = {
    "level_0": {0: 0, 1: 0, 2: 1, 3: 1, 4: 2, 5: 2},
    "level_1": {0: "train", 1: "valid", 2: "train", 3: "valid", 4: "train", 5: "valid"},
    "Start date": {
        0: Timestamp("2021-10-25 17:01:36.508000"),
        1: Timestamp("2021-11-01 17:01:36.879000"),
        2: Timestamp("2021-10-30 13:21:02.925000"),
        3: Timestamp("2021-11-06 13:21:02.346000"),
        4: Timestamp("2021-11-04 09:40:31.312000"),
        5: Timestamp("2021-11-11 09:40:30.249000"),
    },
    "End date": {
        0: Timestamp("2021-11-01 17:01:34.363000"),
        1: Timestamp("2021-11-02 17:01:36.063000"),
        2: Timestamp("2021-11-06 13:20:56.939000"),
        3: Timestamp("2021-11-07 13:21:01.325000"),
        4: Timestamp("2021-11-11 09:40:24.261000"),
        5: Timestamp("2021-11-12 09:40:20.632000"),
    },
    "Period": {
        0: Timedelta("6 days 23:59:57.855000"),
        1: Timedelta("0 days 23:59:59.184000"),
        2: Timedelta("6 days 23:59:54.014000"),
        3: Timedelta("0 days 23:59:58.979000"),
        4: Timedelta("6 days 23:59:52.949000"),
        5: Timedelta("0 days 23:59:50.383000"),
    },
    "Unique days": {0: 574590, 1: 121973, 2: 790379, 3: 79758, 4: 679067, 5: 80585},
    "nbr samples": {0: 575144, 1: 122120, 2: 791209, 3: 79802, 4: 679575, 5: 80640},
}
__df = pd.DataFrame.from_dict(dict_repr)

table_plot = __df
title = "cross-validation folds"
series = "1"
Logger.current_logger().report_table(title=title, series=series, table_plot=table_plot)
# gves error - ValueError: Circular reference detected
```

**Comment by jkhenning** [comment] 2021-12-08 07:57
Well, it seems the problem is with JSON serializing Timedelta objects - these objects contain some sort of self reference (or cross-reference) that impedes JSON's ability to serialize them. The only way to overcome that is to convert them to some base type (for example - number of milliseconds) and convert back on load.

**Comment by ColdTeapot273K** [comment] 2021-12-09 08:03
Yep. 

For those who stumble upon this issue, here's what I think and elegant yet a bit brittle way to solve it. Tailor to your usecase
```python
_df.loc[:, ["Period"]] = _df.loc[:, ["Period"]].transform(
    lambda x: x.dt.round(freq="D").dt.days
)  # INFO: convert to int for ClearML logging
```

**Comment by jkhenning** [comment] 2021-12-09 08:08
@ColdTeapot273K thanks for sharing this! We'll look into the JSON serialization and see how we can better support this - would an automatic serialization be a good solution? In that case I think rounding to days won't be a good default (I assume no rounding at all), but if its important we can add some external way of configuring this in the logger - WDYT?

**Comment by ColdTeapot273K** [comment] 2021-12-09 08:42
@jkhenning since AFAIK you're using `plotly/dash` under the hood the problem is on multiple nodes. Namely, even if you'd have native support for this `pandas.Period` data type, it'd get butchered by `plotly/dash` rendering:

https://i.imgur.com/5gEQhil.png

So i think a reasonable course here would be to throw an exception if certain `pandas` datatypes are not supported by ClearML serialization procedure with a message suggesting for a user to convert them manually. And adding a documentation entry describing what `pandas` datatypes are supported for pandas logging. So that the user can decide wether to bother with custom conversion for fancy report or drop the column altogether to get the job done faster.

I think a Lego-like composability is more important here than a "let me try to do it for you somehow" implicit and potentially brittle logic.

**Comment by jkhenning** [comment] 2021-12-09 09:16
OK, sounds reasonable. I think that in practice, it won't be really practical to check for each type specifically, but since JSON already raises some sort of error, we can simply catch it and issue a more detailed error with some context and a link to examples, sounds good?

**Comment by ColdTeapot273K** [comment] 2021-12-09 13:09
@jkhenning sounds good!

**Comment by jkhenning** [comment] 2021-12-10 19:26
@ColdTeapot273K we might have found a way to support it by using `to_json()` and letting pandas handle it 🙂 - I'll update when an RC with this fix is available

**Comment by jkhenning** [comment] 2021-12-12 19:14
@ColdTeapot273K good news - a new RC 1.1.5rc4 is available with a fix - can you please test and verify?

**Comment by ColdTeapot273K** [comment] 2021-12-15 14:46
@jkhenning tested on 1.1.5rc4, works, nice job!

Wouldn't call it too readable, but that's on `pandas`/`plotly` team. At least it doesn't break now so doesn't make you write ad hoc boilerplate for type conversion.

**Comment by jkhenning** [comment] 2023-03-15 13:37
Closing this issue. Please reopen if required.

**Closed by jkhenning** 2023-03-15 13:37 UTC

**Comment by aurelien-m** [comment] 2023-05-16 13:56
Hello @jkhenning, I'm getting the same issue with this code:
```python
fig = px.scatter(detections, x='distance', y='score', color='label')
Logger.current_logger().report_plotly('Distance vs score', 'Distance vs score', fig)

fig = px.scatter(detections, x='bbox_area', y='score', color='label')
Logger.current_logger().report_plotly('Area vs score', 'Area vs score', fig)
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/aurelien/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/aurelien/Projects/Alteia/detection-chambres-orange/streetview/validate.py", line 169, in <module>
    Logger.current_logger().report_plotly('Area vs score', 'Area vs score', fig)
  File "/home/aurelien/Projects/Venvs/compviz/lib/python3.10/site-packages/clearml/logger.py", line 996, in report_plotly
    self._task._reporter.report_plot(
  File "/home/aurelien/Projects/Venvs/compviz/lib/python3.10/site-packages/clearml/backend_interface/metrics/reporter.py", line 455, in report_plot
    plot = json.dumps(plot, default=default)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
````
I'm on version 1.10.4 of clearml, any ideas?
