### ISSUE TITLE
Frozen worker with large num_workers

### ISSUE THREAD

**Issue by nirraviv** [allegroai/clearml#207] opened 2020-09-10 05:23 UTC
Hi,

I'm running a modified version of your example `pytorch mnist train` (attached below in txt file). When I set the number of workers to large number (e.g. 40) and save my model multiple times, the worker freezes after random number of epochs but always after complete uploading a model:
```
2020-09-10 08:08:32    Test set: Average loss: 0.0268, Accuracy: 9915/10000 (99%)
2020-09-10 08:08:33    2020-09-10 08:08:33,292 - trains.Task - INFO - Completed model upload to file:///data/trains/saved/examples/pytorch mnist train.20e2ad4c4f4247c89d7b7681a0c51d78/models/mnist_cnn.pt
2020-09-10 08:08:34    Train Epoch: 13 [0/60000 (0%)] Loss: 0.019223
```

It happens both when running from `trains-agent` and terminal.

I'm using `trains==0.16.1` and `trains-agent==0.16.0` and python 3.6.
I'm not using docker mode.

Any idea why?

[trains_mnist.txt](https://github.com/allegroai/trains/files/5199282/trains_mnist.txt)

**Comment by bmartinn** [comment] 2020-09-10 09:53
Hi @nirraviv , 
What's the `torch` version you are using ?
Any chance all workers are trying to store the same model at the same time ?
I remember `pytorch-ignite` had a similar problem, and the solution was to make sure only the last model is saved (not node 0, something to do with TPU support)
Could that be the case?

**Comment by nirraviv** [comment] 2020-09-10 11:08
Hi @bmartinn,

Thank you for the quick response, the `torch` version is 1.5.1 (cuda 10.1).
Regarding your second question, I think `torch-ignite` had this problem on distributed model and had to make sure to save on rank 0, here I'm not distributing the model but only using multiple workers in the data loader. Please let me know if I'm wrong or didn't get anything right.

In addition, did you manage to reproduce my problem with the attached code?

**Comment by bmartinn** [comment] 2020-09-12 22:43
Hi @nirraviv,

The good news, I was able reproduce it, the bad news, for some reason after a while one of the pytorch dataloader worker process will die right in the middle of the fork process, once that happens, pytorch will freeze, waiting for the missing worker that will never be.

PyTorch had this kind of behavior back in v1.0 but since then I did not witness something similar. It also doesn't seem to be directly connected with `trains`, but does happen when you initialize `trains` , but only with `output_uri`. Running the same code without passing `output_uri` argument to `Task.init` (i.e. without automatic uploading/copying the model) will not cause it to hang.

Any thoughts?

**Comment by nirraviv** [comment] 2020-09-13 09:29
Hi @bmartinn ,

What is your indication that the dataloader worker died? 

Did you try to manually save the model using `trains`?

**Comment by bmartinn** [comment] 2020-09-13 09:44
> What is your indication that the dataloader worker died?

Lot's of debug prints ;)
And yes fully verified, still can't understand the exact reason.


> Did you try to manually save the model using trains?

This works, what causes the "hang" is saving the model while auto-uploading it, basically seeing this message:
```
2020-09-10 08:08:33    2020-09-10 08:08:33,292 - trains.Task - INFO - Completed model upload to file:///data/trains/saved/examples/pytorch mnist train.20e2ad4c4f4247c89d7b7681a0c51d78/models/mnist_cnn.pt
```

I think I was able to solve it (at least on my machine), could you test the attached wheel (inside the zip)?
Notice that even though it is the same version as the one in PyPi, this is not the same package, so you need to uninstall the installed package and then reinstall manually the attached wheel.
[trains-0.16.2rc0-py2.py3-none-any.zip](https://github.com/allegroai/trains/files/5213874/trains-0.16.2rc0-py2.py3-none-any.zip)

**Comment by nirraviv** [comment] 2020-09-13 11:54
@bmartinn it works perfectly. 
How did you manage to overcome this problem? do you plan to commit this change?

**Comment by bmartinn** [comment] 2020-09-13 12:07
Hi @nirraviv 

>How did you manage to overcome this problem? 

My theory is that if the fork process is taking too long, for some reason (no idea exactly who / why) the sub-process gets killed by the forking main process (I'm still not sure who is in charge of this flow).
`trains` is patching the fork call, so on any sub-process, we still have full auto-magic capabilities.
My suspicion is this patching process sometimes takes a bit too long, and some sort of "watchdog" kills the "failed" fork.
To temporarily overcome this issue, I moved the sub-process patching process to a background thread, so the fork returns immediately. 

> do you plan to commit this change?

I still need to run some tests before this patch can be committed (on the toy example it seems to solve the issue).
Meanwhile, if you can verify this is a stable solution, it will be great :)

**Comment by nirraviv** [comment] 2020-09-13 12:33
I will keep running this version and will notify if I'll encounter any bugs.

Is there a way to use trains-server with the wheel (so it will install the wheel version you sent me and not the PyPi version)?

**Comment by bmartinn** [comment] 2020-09-13 12:47
You can always put a direct http link in the "Installed Packages" section, like you do in any regular `requirements.txt`
The following is an ugly hack, but should do the trick:
```
from trains import Task
task = Task.init('examples', 'debug_wheel')
task.upload_artifact('wheel', '<put_local_path_to_wheel_here>')
```
Then go to the Experiment's Artifact page, and copy the 'wheel' artifact url (hosted on the trains-server)
Now clone your original experiment, then edit the "Installed Packages" and replace the `trains==` with the http link.
As a temporary solution it should hold :)

**Comment by nirraviv** [comment] 2020-09-13 13:53
@bmartinn, It fails to install the wheel.

In the code I inserted the following line:
```
task = Task.init(project_name='examples', task_name='mnist_train')
task.upload_artifact('wheel', '/data/trains/trains-0.16.2rc0-py2.py3-none-any.whl')
```
The copied path is:
```
trains == file:///data/trains/saved/examples/mnist_train.5bd01ea2ce9e49fe9ce355a74773cedc/artifacts/wheel/trains-0.16.2rc0-py2.py3-none-any.whl
```

and the error I get is
```
Processing ./trains==file:/data/trains/saved/examples/mnist_train.5bd01ea2ce9e49fe9ce355a74773cedc/artifacts/wheel/trains-0.16.2rc0-py2.py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/nirr/.trains/venvs-builds.2/3.6/task_repository/sbu_tmp_repo/trains==file:/data/trains/saved/examples/mnist_train.5bd01ea2ce9e49fe9ce355a74773cedc/artifacts/wheel/trains-0.16.2rc0-py2.py3-none-any.whl'
trains_agent: ERROR: Could not install task requirements!
Command '['/home/nirr/.trains/venvs-builds.2/3.6/bin/python', '-m', 'pip', '--disable-pip-version-check', 'install', '-r', '/tmp/cached-reqsbap83ks8.txt']' returned non-zero exit status 1.
```

any idea how to solve this issue?

Note that I also tried it without the file:// prefix.

**Comment by nirraviv** [comment] 2020-09-17 11:32
Hi @bmartinn , 

I still experience this problem once in a while but not in the same frequency as before.

Any other idea why this is happening?

**Comment by elinep** [comment] 2020-09-23 07:55
Hi, 

I experience the same problem using torch dataloader and multiple workers.
I tried `trains-agent==0.15, torch==1.6, trains==0.16.0` and it froze after ~20 `torch.save()`
I also tried `trains-agent==0.15, torch==1.6, trains==0.16.2rc2` it froze after ~50 `torch.save()`

Any update ?

**Comment by bmartinn** [comment] 2020-09-23 22:37
Guys, I have a theory that this is somehow related to the dataloader forking process.
Any chance you can test it with "spawn" instead of "fork" ?
```python
torch.multiprocessing.set_start_method('spawn')
```

**Comment by nirraviv** [comment] 2020-09-29 08:39
Hi @bmartinn,

Switching to "spawn" seems to work (I ran a few tests without any freezing).

But it seems like switching to "spawn" has some conflicts with `trains`. Setting "spawn" after importing `trains` raised the following error
```
RuntimeError: context has already been set
```
and to solve this problem I import `trains` inside the functions after setting multiprocess to "spawn", as you can see in the attached example.

Any idea why or a way to solve this issue?

I'll keep running more tests and will notify if I'll encounter any problem.

[trains_mnist.txt](https://github.com/allegroai/trains/files/5297587/trains_mnist.txt)

**Comment by bmartinn** [comment] 2020-09-29 18:58
@nirraviv yes you are correct :(
python multiprocessing Lock instantiating is the cause of that (there are a few class level Locks instantiated at definition when importing `trains`...)

Your fix is correct, you have to set the "spawn" method before you import trains (this can also be done in global scope).

Does switching to "spawn" method solve the issue ? Is it stable ?
(I'm not saying this is the optimal solution, I'm still trying to nail down the problem itself)

**Comment by nirraviv** [comment] 2020-09-30 06:27
@bmartinn I tried doing it in the global scope but got the same RuntimeError.

For now it seems to solve the issue but I need to run few more tests to be sure.
@elinep did this workaround solved your issue as well?

**Comment by elinep** [comment] 2020-09-30 06:42
Yes, I confirm the fix seems effective for me as well.

**Comment by nirraviv** [comment] 2020-10-01 08:16
BTW, running with "spawn" cause a dramatic degradation in running time (somewhere between 10-20 times slower). 
I think it is a known issue in `pytorch` when using GPU on Linux, so please try to find a better solution with fork :)
If you have another idea please share.

**Comment by bmartinn** [comment] 2020-10-01 22:05
Hi @nirraviv & @elinep  I think this [PR/issue](https://github.com/horovod/horovod/pull/1824) is somewhat related to our case (this is essentially the same problem, where on each forked process we need to setup the new environment because it cannot be directly inherited from the main process).

Based on Horovod's solution, I tested with forkserver (instead of fork/spawn) and things seems to be fast and stable.
Could you also check on your setup?

Example based on the toy data test:
```python
kwargs = {'num_workers': 40, 'pin_memory': True, 'multiprocessing_context': 'forkserver'}
train_loader = torch.utils.data.DataLoader(
        datasets.MNIST(os.path.join('..', 'data'), train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ])),
        batch_size=args.batch_size, shuffle=True, **kwargs)
```

**Comment by nirraviv** [comment] 2020-10-04 13:54
Hi @bmartinn, it seems like both spawn and forkserver are stable and slow. The reason might be the initialization of the worker every epoch. 
To solve it I used the temporary solution suggested   #[here](https://github.com/pytorch/pytorch/issues/15849).

Thank you. I'll let you know if I encounter any more problems with this solution.

**Comment by bmartinn** [comment] 2020-10-04 16:24
This is great news @nirraviv !
I think that your analysis is accurate, this all stems from the fact too many processes are killed and created, instead of reused.
Which seems exactly what the 'forkserver' ( and the aforementioned issue ) solve. Nicely done!

BTW: v0.16.2 is out, with the logging fix included.
```
pip install trains==0.16.2
```

**Closed** 2021-01-17 09:27 UTC
