### ISSUE TITLE
Docker image not pulled by clearml agent

### ISSUE THREAD

**Issue by PhilippeMarcotte** [allegroai/clearml#504] opened 2021-12-01 20:13 UTC
Hello,

I've setup an instance of the clearml server on a kubernetes cluster using the helm chart. I'd like to enqueue a task to execute a simple pytorch script. To do so, I executed the following:
```bash
clearml-task --project test --name pytorch-iris-job --folder ./clearml --queue default --script ./clearml/main_clearml_cpu.py --requirements ./clearml/requirements.txt --docker pytorch/pytorch:latest
```
The command is executed from a windows 10, from a git repo with the access to the clearml server already setup with clearml-init. My problem is the docker image that I specify seems to not be pulled and the code isn't executed in it. It seems to be executed in the default clearml agent's ubuntu docker image. 

I assume it is the case because once it tries to run my script, it complains that pytorch isn't installed which shouldn't be the case if it used the specified docker image. There's also no log regarding pulling a docker image but there are logs regarding installing the requirements found in the requirements.txt

Am I missing something? Is there a specific configuration to do?

Secondly, after looking at the doc quite a bit, I haven't seen how to specify to pull docker images from a different repo than docker hub. We have an internal container repo that I'd like to use.

Thanks.

**Comment by jkhenning** [comment] 2021-12-02 20:43
Hi @PhilippeMarcotte ,

Which ClearML SDK version are you using?

**Comment by jkhenning** [comment] 2021-12-02 21:21
Another idea - is it possible the pytorch version in the requirements is different than the one in the image?

**Comment by PhilippeMarcotte** [comment] 2021-12-02 21:28
I didn't put pytorch in the requirements.txt because I assumed it would already be available in the container and didn't want the agent to reinstall it.

**Comment by PhilippeMarcotte** [comment] 2021-12-02 22:09
So I realized that the clearml agent created by default with the helm chart doesn't use the --docker argument, would that explain why it's not pulling the image?
Here's the command specified in the yaml of the agent-group-cpu-agent deployment
```yaml
      - command:
        - /bin/sh
        - -c
        - apt-get update ; apt-get install -y curl python3-pip git; python3 -m pip
          install -U pip ; python3 -m pip install clearml-agent ; CLEARML_AGENT_K8S_HOST_MOUNT=/root/.clearml:/root/.clearml
          clearml-agent daemon --queue default
```
I tried adding --docker but I get the following error:
clearml_agent: ERROR: Running in Docker mode, 'docker' command was not found

Does it mean the docker mode only works when run directly on a machine, not from inside a container?

**Comment by jkhenning** [comment] 2021-12-02 22:17
> So I realized that the clearml agent created by default with the helm chart doesn't use the --docker argument, would that explain why it's not pulling the image?

Oh no, that's the agent running inside the pod - it's already running within a docker container (the one spun up in the pod).

I think the issue is that you assumed pytorch will be available, but the agent inside the container creates a venv which doesn't have the pytorch installed in it. Try with pytorch in the requirements list and see how it works.

**Comment by tcdnm** [comment] 2022-01-24 11:41
Hi there, thanks for this awesome tool.

I'm having a similar issue. I've installed ClearML community edition on Linux but my tasks are are not running inside a docker container (I am passing the variable --docker with the docker image from dockerhub through the CLI). It's surely not running in the container as I cannot access files within the folder structure of my container. Am I missing some configuration steps?  Thanks.

**Comment by jkhenning** [comment] 2022-01-24 12:24
Hi @tcdnm ,

Which server are you using? Also, can you share the exact command you use to run the ClearML Agent?

**Comment by tcdnm** [comment] 2022-01-24 16:07
I am using the clearml:latest (just installed earlier today with docker-compose) on Ubuntu 20.04 (Docker version 20.10.12). 

The command I'm using to run the agent is the following:

clearml-task --project 'Test' \
             --name test_run \
             --docker tcdnm/test-image:latest \
             --repo https://github.com/tcdnm/clearml-test-docker.git \
             --script test.py \
             --queue training

**Comment by jkhenning** [comment] 2022-01-30 14:52
Good to hear @tcdnm - I'm closing this, please reopen if it's relevant 🙂

**Closed** 2022-01-30 14:52 UTC
