### ISSUE TITLE
Bug：tasks  automatically stop  without manual abort

### ISSUE THREAD

**Issue by zylprivate** [allegroai/clearml#535] opened 2022-01-09 12:36 UTC
I find that the training task suddenly stops recently while I don't abort it.I don't know why.
ClearML Version: V1.1.4 ~ V1.1.5
Linux: Ubuntu18.04
Pytorch:1.8

**Comment by zylprivate** [comment] 2022-01-09 12:39
Info:
clearml.Task - WARNING - ### TASK STOPPED - USER ABORTED - STATUS CHANGED ###
It means I abort it manually but I don't do it.

**Comment by jkhenning** [comment] 2022-01-09 13:36
Hi @zylprivate which server are you using?

**Comment by zylprivate** [comment] 2022-01-09 13:42
I use the default setting. I don't know which server I use. I follow the readme to use it , I think that I might use ClearML Hosted Service.

**Comment by jkhenning** [comment] 2022-01-09 14:01
> I think that I might use ClearML Hosted Service

I assume you've opened an account there? What's the URL you use when accessing an experiment?

**Comment by zylprivate** [comment] 2022-01-09 14:05
Yes, I sign up for an account, the URL  likes that  https://app.community.clear.ml/projects/xxxxx/experiment/xxxx

**Comment by jkhenning** [comment] 2022-01-09 14:11
Well, this message basically means the SDK detected the tack status was changed and is no longer draft, enqueued or in progress, and that the change was not caused by a ClearML Agent.

Did you run the experiment manually from your workstation or using ClearML Agent?

**Comment by zylprivate** [comment] 2022-01-09 14:18
Yes, I  run the experiment manually from my workstation. I only add Task.init into my code. 
The above phenomenon happened yesterday, there was no such situation before. Could this be because I'm using the same account on two different machines?

**Comment by jkhenning** [comment] 2022-01-09 14:35
> Could this be because I'm using the same account on two different machines?

How exactly are you using the same account on two different machines? Are you simply using the same credentials in `clearml.conf`?

**Comment by zylprivate** [comment] 2022-01-09 14:39
No, I create two different App Credentials for different machine.

**Comment by jkhenning** [comment] 2022-01-09 14:44
> No, I create two different App Credentials for different machine.

That should be perfectly fine.

Are you calling `Task.close()` or use multiple processes? Can you try ClearML 1.1.6rc0?

**Comment by zylprivate** [comment] 2022-01-09 14:47
I don't  use `Task.close()`  or use  multiple processes. I will try the new version tomorrow. Thank you very much.

**Comment by SIY1121** [comment] 2022-01-14 09:00
Hi @jkhenning, I have same problem using self-deployd server.
Using the debugger, I found that `_get_status()` sometimes returns `(None, None)` at L33.
After that, it is treated as status_changed at L42.
Perhaps my network connection is unstable, but no retries were made.  (no retrying log output)
https://github.com/allegroai/clearml/blob/0bc43a31f49702077f91ffca2a36d0cb00d7e1a5/clearml/backend_interface/task/development/stop_signal.py#L33-L45

**Comment by jkhenning** [comment] 2022-01-15 21:07
Hi all,

We've just pushed a fix that should address it - can you please try the latest in the master branch?

**Comment by jkhenning** [comment] 2022-09-12 06:10
Hi @SIY1121, closing this. Please re-open if required.

**Closed by jkhenning** 2022-09-12 06:10 UTC
