### ISSUE TITLE
Task.init() registers main process on all available GPUs

### ISSUE THREAD

**Issue by JakobHavtorn** [allegroai/clearml#305] opened 2021-02-08 11:21 UTC
## The issue
When I run experiments I set `CUDA_VISIBLE_DEVICES` to some integer to only make that device available to the main process (as is common). I can verify that this is in fact the case with `sudo fuser -v /dev/nvidia*` which shows that a single process has been created on the single device I chose.

However, I observe that a subsequent call to `Task.init()` in the python script somehow overrides this and “registers” the main process on all GPU devices of the node. This can be seen by inspecting `sudo fuser -v /dev/nvidia*`  after the call to `Task.init()` . The original process ID registered on the device initially chosen with `CUDA_VISIBLE_DEVICES` is now registered on all GPU devices on the node:

```bash
/dev/nvidia0:        jdh        2448 F.... python
/dev/nvidia1:        je          315 F...m python3
                     jdh        2448 F.... python
/dev/nvidia2:        jdh        2448 F.... python
```

I can only see this proces on the other devices when I use `sudo fuser` but not with `gpustat` or `nvidia-smi`. I can also not see any memory being allocated on the other devices.

I’ve verified that `CUDA_VISIBLE_DEVICES` doesn’t get changed during the `Task.init` call or anywhere else during the script.

I’m running manual mode and I only see one GPU tracked in the resource monitoring. I’m using `trains 0.16.4`.

## Reproducing 
You can reproduce simply by taking the ClearML PyTorch MNIST example https://github.com/allegroai/clearml/blob/master/examples/frameworks/pytorch/pytorch_mnist.py.

To clearly see it happening, it’s easiest if you get the GPU allocated before calling `task = Task.init(…)` and to avoid crashing because you’re missing the task variable, you can embed just before and after `Task.init(…)` using `IPython`.  You also need the process ID of the main process to use to check against `sudo fuser -v /dev/nvidia*`.

Summarizing, I move `task = Task.init(…)` to just before the for epoch in `range(…)` loop and replace it with

```python
import psutil
current_process_pid = psutil.Process().pid
print(current_process_pid)  # e.g 12971
import IPython; IPython.embed()
task = Task.init(project_name='examples', task_name='pytorch mnist train')
import IPython; IPython.embed()
```

You can then run the example until it reaches the embed and check that the main process printed is only visible on your designated device. Then you can quit the embed to see the `Task.init` giving the problem after which you are waiting in the second embed. You can then quit that one to see training work fine.

You can then try the whole thing again without `Task.init` but you need to remove reporting in that case - otherwise you get

```python
Logger.current_logger().report_scalar(
AttributeError: 'NoneType' object has no attribute 'report_scalar'
```

I haven’t tested on any other versions than `trains 0.16.4` so I don’t know if it happens in the new clearml package.

**Comment by bmartinn** [comment] 2021-02-11 22:14
Hi @JakobHavtorn 
Does that happen on manual execution (i.e. running the code manually) or is it an issue when running with `clearml-agent` ?
I double checked the code, and it does not change the "CUDA_VISIBLE_DEVICES" variable, see [here](https://github.com/allegroai/clearml/search?q=CUDA_VISIBLE_DEVICES)
Could you test with the latest `clearml` (`pip install clearml==0.17.5rc3`) 
BTW: you have nothing to worry about, it is fully backwards compatible (yes even with older `trains-server` versions 😄 )

**Comment by JakobHavtorn** [comment] 2021-02-12 13:15
> Does that happen on manual execution (i.e. running the code manually) or is it an issue when running with clearml-agent ?
This is observed with manual execution. I have not examined the behaviour with the agent.

> I double checked the code, and it does not change the "CUDA_VISIBLE_DEVICES" variable, see here
Thank you. That's also in line with my observations that it does not change at any point during the script execution.

> Could you test with the latest clearml (pip install clearml==0.17.5rc3)?
It still happens in the same way reported above.

The system I'm running on is
- Ubuntu 18.04.1 LTS
- CUDA 10.1
- CuDNN 7.6.5
- GPUs: GeForce GTX 1080 Ti / TITAN X (Pascal) / GeForce GTX TITAN X

**Comment by bmartinn** [comment] 2021-02-12 20:42
Hmm @JakobHavtorn can you verify that if the `Task.init` is removed the  `CUDA_VISIBLE_DEVICES` does not change ?
Also, could you try setting `CUDA_DEVICE_ORDER=PCI_BUS_ID` and `NVIDIA_VISIBLE_DEVICES` as well ?

My theory is that this is a `pytorch` issue, unrelated to `clearml`, maybe it connects with https://github.com/pytorch/pytorch/issues/20606

**Comment by JakobHavtorn** [comment] 2021-02-12 20:58
We have never had issues with the wrong devices being used by PyTorch as reported in that issue. I recon this is because `CUDA_DEVICE_ORDER` is `PCI_BUS_ID` by system default. I'll verify this and get back to you. 

Also, as reported above, the issue only happens when `Task.init` is called. I'd be surprised about a PyTorch related issue. 

But I'll `NVIDIA_VISIBLE_DEVICES` as well and verify `CUDA_DEVICE_ORDER` and get back with the result.

**Comment by bmartinn** [comment] 2021-02-12 21:27
Thanks @JakobHavtorn ! Let me know what you find ...
Anyhow, I'll keep trying to reproduce it locally.

**Comment by JakobHavtorn** [comment] 2021-02-12 21:31
Thanks @bmartinn.

I'm running 1.7.

**Comment by JakobHavtorn** [comment] 2021-02-15 13:08
I've now verified that `CUDA_DEVICE_ORDER== PCI_BUS_ID` and that setting `NVIDIA_VISIBLE_DEVICES` in addition to `CUDA_VISIBLE_DEVICES` does not change the behaviour.

**Comment by bmartinn** [comment] 2021-02-15 16:08
Hey @JakobHavtorn, could you run the following code and let me know what you are getting ?
(because I cannot understand what's going on, nor can I reproduce it...)

``` python
import os
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['NVIDIA_VISIBLE_DEVICES'] = '0'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

from clearml import Task

print(os.environ)
print('current_device', torch.cuda.current_device())
task = Task.init('examples', 'testing CUDA_VISIBLE_DEVICES')
print(os.environ)
print('current_device', torch.cuda.current_device())
```

**Comment by JakobHavtorn** [comment] 2021-02-15 16:44
I took the liberty and also printed the main process ID to match them up.

I can verify that this minimal example **also** results in the replication of the process onto all available devices **after** `Task.init(...)`.

```python
import os
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['NVIDIA_VISIBLE_DEVICES'] = '0'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

import psutil

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets

from clearml import Task

current_process_pid = psutil.Process().pid
print(current_process_pid)

print(os.environ)
print('current_device', torch.cuda.current_device())
task = Task.init('examples', 'testing CUDA_VISIBLE_DEVICES')
print(os.environ)
print('current_device', torch.cuda.current_device())
```

I get the following, where I have removed the large `LS_COLORS` variable, `SSH` related info and replace the ClearML server address with XX.XX.XXX.XX.

```
535
environ({'CONDA_DEFAULT_ENV': 'infotropy', 'CONDA_EXE': '/home/jdh/anaconda3/bin/conda', 'CONDA_PREFIX': '/home/jdh/anaconda3/envs/infotropy', 'CONDA_PREFIX_1': '/home/jdh/anaconda3', 'CONDA_PROMPT_MODIFIER': '(infotropy) ', 'CONDA_PYTHON_EXE': '/home/jdh/anaconda3/bin/python', 'CONDA_SHLVL': '2', 'CUDA_DEVICE_ORDER': 'PCI_BUS_ID', 'CUDA_HOME': '/usr/local/cuda', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1009/bus', 'HOME': '/home/jdh', 'LANG': 'en_US.UTF-8', 'LANGUAGE': 'en_US.UTF-8', 'LC_ALL': 'en_US.UTF-8', 'LC_CTYPE': 'en_US.UTF-8', 'LC_TERMINAL': 'iTerm2', 'LC_TERMINAL_VERSION': '3.4.3', 'LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64', 'LOGNAME': 'jdh', 'MAIL': '/var/mail/jdh', 'OMF_CONFIG': '/home/jdh/.config/omf', 'OMF_PATH': '/home/jdh/.local/share/omf', 'ORIGINAL_LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64', 'PATH': '/home/jdh/anaconda3/envs/infotropy/bin:/home/jdh/anaconda3/bin:/home/jdh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin', 'PWD': '/home/jdh/repos/infotropy/results', 'SHELL': '/usr/bin/fish', 'SHLVL': '1', 'SSH_TTY': '/dev/pts/9', 'TERM': 'xterm-256color', 'USER': 'jdh', 'XDG_RUNTIME_DIR': '/run/user/1009', 'XDG_SESSION_ID': '49548', 'NVIDIA_VISIBLE_DEVICES': '0', 'CUDA_VISIBLE_DEVICES': '0'})
current_device 0
ClearML Task: overwriting (reusing) task id=450b031e0a1f47faa5f77ea528732294
2021-02-15 16:40:55,437 - clearml.Repository Detection - WARNING - Can't get branch information for git repo in /home/jdh/anaconda3/envs/infotropy/bin
2021-02-15 16:40:55,448 - clearml.Repository Detection - WARNING - Can't get commit information for git repo in /home/jdh/anaconda3/envs/infotropy/bin
2021-02-15 16:40:55,458 - clearml.Repository Detection - WARNING - Can't get root information for git repo in /home/jdh/anaconda3/envs/infotropy/bin
2021-02-15 16:40:55,469 - clearml.Repository Detection - WARNING - Can't get status information for git repo in /home/jdh/anaconda3/envs/infotropy/bin
ClearML results page: http://XX.XX.XXX.XX:8080/projects/45d9e65cf2b44e539110d6df451da2c1/experiments/450b031e0a1f47faa5f77ea528732294/output/log
2021-02-15 16:40:55,494 - clearml.Repository Detection - WARNING - Can't get diff information for git repo in /home/jdh/anaconda3/envs/infotropy/bin
environ({'CONDA_DEFAULT_ENV': 'infotropy', 'CONDA_EXE': '/home/jdh/anaconda3/bin/conda', 'CONDA_PREFIX': '/home/jdh/anaconda3/envs/infotropy', 'CONDA_PREFIX_1': '/home/jdh/anaconda3', 'CONDA_PROMPT_MODIFIER': '(infotropy) ', 'CONDA_PYTHON_EXE': '/home/jdh/anaconda3/bin/python', 'CONDA_SHLVL': '2', 'CUDA_DEVICE_ORDER': 'PCI_BUS_ID', 'CUDA_HOME': '/usr/local/cuda', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1009/bus', 'HOME': '/home/jdh', 'LANG': 'en_US.UTF-8', 'LANGUAGE': 'en_US.UTF-8', 'LC_ALL': 'en_US.UTF-8', 'LC_CTYPE': 'en_US.UTF-8', 'LC_TERMINAL': 'iTerm2', 'LC_TERMINAL_VERSION': '3.4.3', 'LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64', 'LOGNAME': 'jdh', 'MAIL': '/var/mail/jdh', 'OMF_CONFIG': '/home/jdh/.config/omf', 'OMF_PATH': '/home/jdh/.local/share/omf', 'ORIGINAL_LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64', 'PATH': '/home/jdh/anaconda3/envs/infotropy/bin:/home/jdh/anaconda3/bin:/home/jdh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin', 'PWD': '/home/jdh/repos/infotropy/results', 'SHELL': '/usr/bin/fish', 'SHLVL': '1', 'SSH_TTY': '/dev/pts/9', 'TERM': 'xterm-256color', 'USER': 'jdh', 'XDG_RUNTIME_DIR': '/run/user/1009', 'XDG_SESSION_ID': '49548', 'NVIDIA_VISIBLE_DEVICES': '0', 'CUDA_VISIBLE_DEVICES': '0', 'CLEARML_PROC_MASTER_ID': '535:450b031e0a1f47faa5f77ea528732294', 'TRAINS_PROC_MASTER_ID': '535:450b031e0a1f47faa5f77ea528732294'})
current_device 0```

**Comment by bmartinn** [comment] 2021-02-15 16:56
Thanks @JakobHavtorn! 
What I'm seeing is the expected (correct) behavior, no?
There is no change to either the NVIDIA_VISIBLE_DEVICES/CUDA_VISIBLE_DEVICES nor to the `torch.cuda.current_device()`

What am I missing here?

**Comment by JakobHavtorn** [comment] 2021-02-16 14:41
Thanks for taking the time @bmartinn.

I'll try to be more clear:

### The problem

If run the above code, and leave the main process alive (e.g. by `IPython.embed()` or `time.sleep(60)`), and check `sudo fuser -v /dev/nvidia*`, I can see that the main process is "registered" on all devices. 

The "problem" is that this **only** happens when `Task.init(...)` is called and that it happens despite `CUDA_VISIBLE_DEVICES` and `NVIDIA_VISIBLE_DEVICES` both being set to a specific device and `CUDA_DEVICE_ORDER==PCI_BUS_ID`.

Through the above, we have confirmed that neither `CUDA_VISIBLE_DEVICES` or `NVIDIA_VISIBLE_DEVICES` gets changed by `Task.init(...)`, so there must be something else causing the main process to figure on all devices in `sudo fuser -v /dev/nvidia*`.


### My concerns

I have not observed that it has any impact on performance, I'm just slightly wary about this behaviour. It can look pretty crazy with 10 experiments all being tracked at the same time (a lot of processes listed on the GPUs).

The [official documentation](https://man7.org/linux/man-pages/man1/fuser.1p.html) of `fuser` says

> fuser — list process IDs of all processes that have one or more files open

Is it expected behaviour that the main process "opens one or more files" on each of the GPUs even though we only select one with `CUDA_VISIBLE_DEVICES`?

Maybe it has something to do with the resource monitoring? Is that expected to make the main process ID visible on all devices?

**Comment by bmartinn** [comment] 2021-02-17 00:30
@JakobHavtorn I think I have a theory, it might be the GPU monitoring itself that is registered on all GPUs (it will have no effect on anything else but might cause the `fuser` to display the process as "running" on all GPUs)
Here is a quick test, let's see if you get the same behavior if we shutdown the monitoring by passing `auto_resource_monitoring=False` to the `Task.init` call:

``` python
import os
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['NVIDIA_VISIBLE_DEVICES'] = '0'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

from clearml import Task

print(os.environ)
print('current_device', torch.cuda.current_device())
task = Task.init('examples', 'testing CUDA_VISIBLE_DEVICES', auto_resource_monitoring=False)
print(os.environ)
print('current_device', torch.cuda.current_device())
```

**Comment by JakobHavtorn** [comment] 2021-02-18 12:52
This does the trick. When `auto_resource_monitoring==False` the main process does not "run" on all GPUs. 

Contrary, setting `auto_resource_monitoring==True` results in the same behaviour as reported above with the main process "running" on all devices.

**Comment by bmartinn** [comment] 2021-02-18 22:40
Okay, I think we found it!
I'm assuming somewhere when we use the nvidia pynvm and query the GPUs `fuser` registers it as open files on all GPUs.
I'm actually not sure if we could somehow disable the query since the pynvm query reruns statistics on all GPUs but the "resource monitor" will only report the ones that are active based on `NVIDIA_VISIBLE_DEVICES`.
WDYT?

**Comment by JakobHavtorn** [comment] 2021-03-12 13:50
Sorry for going AWOL here.

Indeed it seems we found it. I'm not sure what to do about it. If `pynvm` runs the checks on all devices by default and it cannot be modified, then that's that. It does seem that `pynvm` is a somewhat [stale project](https://github.com/perone/pynvm) not having been updated the last 5 years? Maybe there's something better and more manageable out there?

**Comment by bmartinn** [comment] 2021-03-13 23:23
No worries @JakobHavtorn :)

BTW, my mistake this is not `pynvm` but it is `pynvml`,  apologies :( different [project](https://github.com/gpuopenanalytics/pynvml) and a well maintained one!

The issue is that I'm not sure we can work around the access thing, as the query itself to the `nvidia-smi` driver is registered on all GPUs (which makes sense in a way), but for our purpose we need to check if querying a single GPU will not trigger all of them.

Could you test this code and check if the calling process is registered on all GPUs ?

```python
from time import sleep
from pynvml import *
nvmlInit()
selected_devices = (0, )
selected_handles = [nvmlDeviceGetHandleByIndex(i) for i in selected_devices]
while True:
    for handle in selected_handles:
        print(nvmlDeviceGetMemoryInfo(handle).used)
    sleep(1)
```

**Comment by JakobHavtorn** [comment] 2021-03-27 19:07
It is indeed registered on all devices 👍

**Comment by bmartinn** [comment] 2021-03-28 00:40
Thanks @JakobHavtorn 
If that is the case, then sadly we just proved that even if initializing the query on a single GPU, all GPUs are registered under the same process.
Nothing we can do about it, at least we proved this is just a "cosmetic" issue  :)

**Comment by JakobHavtorn** [comment] 2021-03-28 18:40
All right, I can live with that! As long as there's no performance implications 😉

**Comment by bmartinn** [comment] 2021-03-29 23:59
Sounds good, closing this issue for now, if anything comes up, please re-open.

**Closed by bmartinn** 2021-03-29 23:59 UTC
