### ISSUE TITLE
Separate console logs from different runs

### ISSUE THREAD

**Issue by michaelitvin** [allegroai/clearml#162] opened 2020-07-02 07:35 UTC
Scenario:
Run training in one process, with `Task.init()`.
Run evaluation in another process and write to the same task with `Task.get_task(task_id='abcd1234')`.

Current outcome:
Console logs of both processes come out interlaced in Trains.

Possible desired outcome:
Separate console logs, one for each process.

**Comment by bmartinn** [comment] 2020-07-02 11:03
@michaelitvin the issue is verified, and already fixed on the master branch.

The bug itself is that `Task.get_task` should not auto-log the console output (only `Task.init` should do that)

If you want to report logs to the "external" task , you can always do:
```python
external_task = Task.get_task(task_id='abcd1234')
external_task.get_logger().report_text('hello from another process')
```

You can verify it was fixed, by installing directly from the git:
```bash
pip install -U git+https://github.com/allegroai/trains.git
```

**Comment by michaelitvin** [comment] 2020-07-02 11:28
Cool!
So mentioning #160 in this context.

**Comment by bmartinn** [comment] 2020-07-07 19:32
Hi @michaelitvin 
Just updating here, the latest RC contains the fix.
You can install with:
```bash
pip install trains==0.15.2rc0
```

**Comment by michaelitvin** [comment] 2020-07-07 19:49
Does it come with a way to restart automagical logging?

**Comment by bmartinn** [comment] 2020-07-10 20:31
@michaelitvin what do you mean by "restart automagical logging"?
When calling `Task.get_task` there should not be any automagical logging, this was the bug :)

**Comment by michaelitvin** [comment] 2020-07-10 22:24
That thing we discussed in another thread, that sometimes a training task stops (e.g. another user killed it, or I decided to pause it for some reason), and I want to restart it later on and continue logging loss, learning rate and console from the point it stopped.
So this bug was actually a feature to me:)

**Comment by bmartinn** [comment] 2020-07-11 12:49
Sure, you mean #160 :)
Let's close this issue and leave #160 open, as it is now a new feature (which hopefully will be pushed soon :)

**Closed** 2021-01-17 08:59 UTC
