### ISSUE TITLE
Deadlocks happening with version `1.4.0`

### ISSUE THREAD

**Issue by alekpikl** [allegroai/clearml#674] opened 2022-05-11 16:22 UTC
After upgrading `clearml` to `1.4.0,` our code started producing deadlocks that had not been happening before.

The part of our code that was caught in a deadlock was inside `multiprocessing.Pool()`. 

We used Python3.8 and Tensorflow2.8. We use `ClearML` for experiment tracking only. We create `Task` objects manually and report scalars using `clearml.Logger.report_scalar()`. 

Disabling `clearml` solved the issue. We pinpointed https://github.com/allegroai/clearml/commit/7625de3f2fec0eb641024ce7ca70a7d31083fa23 as the culprit. Downgrading to the commit before solved the problem. 

We noticed that you patched the OS forking 👇 , which _may cause_ weird issues like ours.
https://github.com/allegroai/clearml/blob/bca9a6de3095f411ae5b766d00967535a13e8401/clearml/binding/environ_bind.py#L61 

After commenting out this line, 
https://github.com/allegroai/clearml/blob/bca9a6de3095f411ae5b766d00967535a13e8401/clearml/task.py#L628-L629
the deadlock did not happen anymore. Disclaimer, we did not test this. The purpose was to get a quick feeling if this hypothesis has merit. 

You probably have reasons for pathing the os forking mechanism; however, from reading the comments in that part of the code, it is not entirely clear what root cause you're solving.

**Comment by jkhenning** [comment] 2022-05-11 18:53
Hi @alekpikl, 

You're absolutely right - our apologies 🙏 🙁
We do have an internal test that should have caught it... I'll check why our automated testing pipeline failed to detect that.

We'll release an RC as soon as possible, will update here

**Comment by jkhenning** [comment] 2022-05-12 20:55
Hi @alekpikl, @vlad-ivanov-name,

Updating that a new ClearML SDK v1.4.1rc0 is out with a fix for this issue, please update if the issue is resolved 🙏

**Comment by bmartinn** [comment] 2022-05-12 21:08
Hi @alekpikl 
> How important is os.fork patching for experiment tracking? 

In short very 🙂 The issue is that without addressing the fork issue, all the "original" threads and thread queues/locks are not actually available, which means that first that are not to be used, and second data still needs to flow to the subprocess which actually does the reporting / uploading. 

> Would it be feasible to have an option to disable it, perhaps at the cost of some functionality?

In theory yes it would be possible, but than we loos all logging capabilities from sub-processes (for example sub-process writing to console will not be logged)

> Just a thought but I feel like environments and tools like e. g. tensorflow are already quite fragile ...

Actually from our experience, the fragile part is actually python... but your point stands. Notice that the TF subprocesses are not effected by the patched forked (they are in most cases low level C++ subprocesses , so no python code can actually make a difference there). PyTorch DataLoader was the main reason we started optimizing for forked processes, because these are python subprocesses and you do want the ability to have access to the logging capabilities from these subprocesses.

Does that make sense ?

**Comment by alekpikl** [comment] 2022-05-13 10:27
> Updating that a new ClearML SDK v1.4.1rc0 is out with a fix for this issue, please update if the issue is resolved 🙏

This resolves the issue. Thank you for the fast response and the fix! 🙏

**Comment by tomer-grin** [comment] 2022-07-20 09:10
@bmartinn 
I believe we got this issue again in version 1.6.3.
Is it possible?
(removed the clearml functionality from the function and it works as expected)

**Comment by tomer-grin** [comment] 2022-07-20 13:57
@morsinai13
Yes, 
```
    refocus_frame_and_save_patial = partial(refocus_frame_and_save, output_dump_subfolder, model_path, kwargs)
    with Pool(min(len(summary_sharp_refocus_json['frames']), os.cpu_count())) as pool:
        results = pool.map(refocus_frame_and_save_patial, summary_sharp_refocus_json['frames'])
```

`refocus_frame_and_save`
Contains `Logger` class calls and methods (`report_vector`, `report_image` etc..)

**Closed** 2023-03-15 15:34 UTC
