### ISSUE TITLE
unable to load image when using / in the project name

### ISSUE THREAD

**Issue by davidenitti** [allegroai/clearml#584] opened 2022-02-18 11:11 UTC
when I use the slash / in the project name (to put the project in subprojects e.g. classification/project1) I cannot visualize the images.
I realized that the images are save in the directory e.g. classification%2Fproject1, and the url contains the same, but since % is a special character the url should be classification%252Fproject1, that's why it does not work.
if there is another way to put the experiments in a subprojects (automatically) and avoid this issue let me know.

**Comment by davidenitti** [comment] 2022-02-22 14:45
thanks

**Comment by eugen-ajechiloae-clearml** [comment] 2022-02-24 20:01
Hi @davidenitti,

I was not able to reproduce this. I was able to access the image just fine. The link where the image is stored at looks like this for me `https://files.clear.ml/bugs%252Freproduce/Image%20reporting.....`.
This is the code I used to try reproduce this:
```
import numpy as np

from clearml import Task


def report_debug_images(logger, iteration=0):
    m = np.eye(256, 256, dtype=np.float)
    logger.report_image("image/bug", "image float", iteration=iteration, image=m)


def main():
    task = Task.init(project_name="bugs/reproduce", task_name="Image reporting")
    logger = task.get_logger()
    report_debug_images(logger)
    logger.flush()


if __name__ == "__main__":
    main()
```

Am I missing something? 

Thanks!

**Comment by davidenitti** [comment] 2022-02-25 10:15
@eugen-ajechiloae-clearml thanks, I realized now that the problem is only when I save the data offline and then I import them.
can you try to use the same code in this example with offline_mode and then import it?
thank you very much!

**Comment by eugen-ajechiloae-clearml** [comment] 2022-02-25 21:45
@davidenitti Was able to reproduce it now. Hopefully we will fix this soon :)

**Comment by davidenitti** [comment] 2022-03-04 10:23
@eugen-ajechiloae-clearml thanks, do you know if the bug is client side or server side?

**Comment by eugen-ajechiloae-clearml** [comment] 2022-03-04 14:59
@davidenitti the issue is client side. We already have a PR for the fix it that awaits review

**Comment by davidenitti** [comment] 2022-03-10 17:22
ok thanks

**Comment by eugen-ajechiloae-clearml** [comment] 2022-03-10 20:24
@davidenitti After code review, we concluded that you should actually quote that link  further down in the code for better results:

```
    image["source"] = "/".join([remote_url, pre + ".{}".format(task_id), post]):
    if debug_sample not in uploaded_files and debug_sample.is_file():
        uploaded_files.add(debug_sample)
        StorageManager.upload_file(local_file=debug_sample.as_posix(), remote_url=image['source'])
        image["source"] = quote_url(image["source"])   # <------ here
```

**Comment by erezalg** [comment] 2022-03-24 09:45
@davidenitti ,
We have an RC ready for this issue, install it by running pip install clearml==1.3.2rc1C
Let us know if this solves the issue

**Comment by erezalg** [comment] 2022-05-05 17:31
Hi @davidenitti,

Did you get a chance to test whether this issue is resolved or not?

**Comment by jkhenning** [comment] 2023-03-15 15:32
Closing this as it was already released. Please reopen if required.

**Closed by jkhenning** 2023-03-15 15:32 UTC
