### ISSUE TITLE
Direct Plotly reporting does not retain colorscale.

### ISSUE THREAD

**Issue by RobinBaumann** [allegroai/clearml#373] opened 2021-05-31 12:18 UTC
Hi together,

first of all: I am aware of this issue: #247 and read through the conversation.

I currently face a somehow related problem, when I try to directly report a plotly figure via `Logger.report_plotly`.  I have a model for 3D reconstruction on neural implicit representations and want to log debug samples as 3D scatter plots, where the color of each point encodes the distance of the point to the surface. When I create the figure and save it as a static image, Everything works as expected, but when I report the figure to ClearML, all points have the same color in the dashboard, even if I explicitly specify a `colorscale` for my plot.

This is the code that I use to create the scatter plot:

```python
import numpy as np
import plotly.graph_objects as go

def plot_vertices(model, c=None, cmap=None, alpha=0.7, title=''):
  marker_data = go.Scatter3d(
      x=model[:, 0],
      y=model[:, 1],
      z=model[:, 2],
      marker=go.scatter3d.Marker(size=3,
                                 color=c if c is not None else None,
                                 colorscale=cmap if cmap else None,
                                 ),
      opacity=alpha,
      mode='markers'
  )

  layout = go.Layout(
      scene=dict(
          camera=dict(up=dict(x=0, y=1, z=0),
                      eye=dict(x=0, y=1, z=2.5),
                      ),
          aspectmode='data',
      ),
      width=480,
      height=640,
      title=title,
      title_x=0.5
  )

  fig = go.Figure(data=marker_data,
                  layout=layout)
  return fig
```

and I report the figure using:

```python
figure = plot_vertices(X, c=y)
clearml_logger.report_plotly(title=name, series='debug',
                                      figure=figure, iteration=step)
```

**Comment by ainoam** [comment] 2021-05-31 15:20
Thanks for pointing this out @RobinBaumann.
The next ClearML server release should include a fix that will not override existing coloring in reported plots.

**Comment by eliorc** [comment] 2021-07-29 05:23
This is not solved in `clear-ml` server 1.1, I'm experiencing the same issue with `go.Parcoords` and `clear-ml` server 1.1

**Comment by jkhenning** [comment] 2021-07-29 08:12
Hi @eliorc ,

We'll take a look - can you send a small reproducing task code?

**Comment by eliorc** [comment] 2021-07-29 09:21
@jkhenning sure

```python3
import plotly.graph_objects as go

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/parcoords_data.csv")

fig = go.Figure(data=
    go.Parcoords(
        line = dict(color = df['colorVal'],
                   colorscale = 'Electric',
                   showscale = True,
                   cmin = -4000,
                   cmax = -100),
        dimensions = list([
            dict(range = [32000,227900],
                 constraintrange = [100000,150000],
                 label = "Block Height", values = df['blockHeight']),
            dict(range = [0,700000],
                 label = 'Block Width', values = df['blockWidth']),
            dict(tickvals = [0,0.5,1,2,3],
                 ticktext = ['A','AB','B','Y','Z'],
                 label = 'Cyclinder Material', values = df['cycMaterial']),
            dict(range = [-1,4],
                 tickvals = [0,1,2,3],
                 label = 'Block Material', values = df['blockMaterial']),
            dict(range = [134,3154],
                 visible = True,
                 label = 'Total Weight', values = df['totalWeight']),
            dict(range = [9,19984],
                 label = 'Assembly Penalty Wt', values = df['assemblyPW']),
            dict(range = [49000,568000],
                 label = 'Height st Width', values = df['HstW'])])
    )
)
```

My plot uses different data, but technically its the same plot.
This is how the plot I am using (again, the same as above with different data) looks like on my jupyter notebook
![juptyer](https://user-images.githubusercontent.com/17727283/127466574-263c9a1c-3f08-4805-a002-b69cb680cdeb.png)

and this is how it looks in the ClearML UI (clearml-server 1.1.0)
![clearml](https://user-images.githubusercontent.com/17727283/127466798-e01b607b-5c72-4448-b9d7-85197391669b.png)

**Comment by bmartinn** [comment] 2021-07-29 20:21
Hi @eliorc 
Quick update, this should have been fixed in `clearml-server` 1.1, a hot patch will be released after the weekend with this fix included 😄

**Comment by eliorc** [comment] 2021-08-08 07:32
@bmartinn the color seems to be fixed with the new release from two days ago, but the plot is still wrong.

I'm using the same data exactly to plot (I literally downloaded the data from the task itself to reproduce) and some lines are missing.

This is the (now with color!) plot from the server:
![image](https://user-images.githubusercontent.com/17727283/128624533-ed0ee947-f959-430a-9f2d-cdc0d1033a4f.png)


And this is the plot using the same data, in a Jupyter notebook:
![image](https://user-images.githubusercontent.com/17727283/128624550-3c9543cf-566e-4bfd-9b6f-07f4da50dfdf.png)


Notice that the lines with value 0, are missing

**Comment by bmartinn** [comment] 2021-08-09 00:50
Hi @eliorc 
Can you send a toy example to reproduce the issue?
(could it be the color of 0 is actually white, and this is why we do not see the lines? the main suspicion is that you can still see the y-axis "mean" , "median" tags)

**Comment by eliorc** [comment] 2021-08-09 05:21
Yes attaching here code and data to reproduce

For data, copy the text here into your clipboard:
[pandas_clipboard.txt](https://github.com/allegroai/clearml/files/6952244/pandas_clipboard.txt)

Then, to plot this in Jupyter, run the following:

```python3
import plotly.graph_objects as go
import numpy as np
import pandas as pd

# Read data from clipboard
hp_table = pd.read_clipboard()

# Build the dimensions argument for the Parcoords plot
dimensions = list()

# Iterate over the columns
loss_name = "dre_0.5"
for column in hp_table.columns:

    # Skip the columns that are not hyperparameters (loss and trial_id)
    if column in {loss_name, 'trial_id'}:
        continue

    # Categorical parameters
    if hp_table[column].dtype == 'object':

        # For categorical parameters, we need to convert values into integers, and map them to the text we want
        # assigned to them, see example here: https://plotly.com/python/parallel-coordinates-plot/
        mapping = hp_table[column].unique()
        dimensions.append({'range': [0, len(mapping)],
                           'tickvals': list(range(len(mapping))),
                           'ticktext': mapping,
                           'label': column,
                           'values': hp_table[column].apply(lambda x: np.where(mapping == x)[0][0])})

    # Numerical parameters
    else:
        # Use minimum range of 0 or minimum, to include None's in the plot (Nones are plotted as zeros)
        dimensions.append({'range': [min(hp_table[column].min(), 0),
                                     hp_table[column].max() + hp_table[column].max() * 0.1],
                           'label': column,
                           'values': hp_table[column]})

# Create figure
fig = go.Figure(data=go.Parcoords(
    line={'color': hp_table[loss_name],
          'colorscale': 'Inferno',
          'showscale': True,
          'colorbar': {'title': loss_name},
          'reversescale': False},
    dimensions=dimensions))

fig.show()
```

Then you can use the same code exactly to use `logger.report_plotly` and see the difference

**Comment by bmartinn** [comment] 2021-08-11 21:19
Thanks @eliorc 
I was able to verify, and it seems that for some reason, as suspected, the 0 value color is white ...
I'll update here when a patch is out

**Comment by eliorc** [comment] 2021-08-12 05:07
@bmartinn happy to help

any workaround for the mean time? is there a way to hard code the color of 0?

**Comment by bmartinn** [comment] 2021-08-13 22:14
I suspect this is a `plotly.js` issue and that we should upgrade the version the web app is using.
(nothing we can do from the python side)

**Comment by eliorc** [comment] 2021-08-15 07:45
So this issue should be transferred to clearml-server?

**Comment by bmartinn** [comment] 2021-08-15 23:21
Okay we sorted it out, it seems that you had NaNs in the data, which were translated into `'nan'`, plotly will not draw `'nan'`s, this is a design decision. But when plotly.py generated the plots for plotly (i.e. plt.show()), it replaced the NaNs with `null`, which plotly.js will draw.
Long story short, a fix will be pushed tomorrow, no need to upgrade the server :)

**Comment by bmartinn** [comment] 2021-08-19 21:42
@eliorc could you verify the issue is fixed ?
Install directly from the git repository:
```
pip install git+https://github.com/allegroai/clearml.git
```

**Comment by eliorc** [comment] 2021-08-22 05:32
> git+https://github.com/allegroai/clearml.git

Solved :)

**Comment by bmartinn** [comment] 2021-08-31 22:30
> Chevked and verified, solved :)

Great news and now the RC is also out:
```
pip install clearml==1.0.6rc1
```

**Closed by bmartinn** 2021-08-31 22:30 UTC
